### ISSUE TITLE
is there a docker image for A100？

### ISSUE THREAD

**Issue by 520jefferson** [TsinghuaAI/CPM-1-Generate#45]
The training process using V100 with cuda10.X.
When i use the A100, the torch version will be 1.7.0. 
If i use the docker image you provide, there will be some error. 
whether there is a docker image for gpu machine A100   ?

**Comment by zzy14** [comment]
Currently not. We don't have A100 servers. Maybe you can use the latest docker image provided by DeepSpeed.
