### ISSUE TITLE
zero-shot 精度测试

### ISSUE THREAD

**Issue by gjm441** [TsinghuaAI/CPM-1-Generate#46]
您好，能否提供阅读理解CHID，CMR2018，C3的脚本？
使用CPM-large测试OCNLI、TNEWS，精度分别为0.442，0.3278（3278/10000），是不是有问题？

**Comment by zzy14** [comment]
Finetune的脚本可以参考 https://github.com/TsinghuaAI/CPM-1-Finetune。另外测试的脚本是使用[这个](https://github.com/TsinghuaAI/CPM-1-Generate#%E5%88%86%E7%B1%BB%E4%BB%BB%E5%8A%A1%E9%9B%B6%E6%AC%A1%E5%AD%A6%E4%B9%A0zero-shot-learning)吗？

**Comment by Chunhui-Zou** [comment]
我复现的精度也是这样

**Comment by zzy14** [comment]
Hi 之前代码默认的TNEWS测试标签集合为完整标签集合，而论文汇报的为采样标签集合，采样标签集合的更加简单，所以准确率更高。现在代码已修改默认配置为采样标签集合。
