### ISSUE TITLE
top_k，top_p如何设置提高生成结果的质量

### ISSUE THREAD

**Issue by zhenhao-huang** [TsinghuaAI/CPM-1-Generate#50]
‘top_k’，‘top_p’取多少可以提高生成结果的质量，`temperature`目前最好是取`0.9`吗

**Comment by zzy14** [comment]
这个质量取决于具体的需求，比如做QA需要精准的答案，那top_k=1可能比较好，给出唯一确定的结果，如果做对话，需要更好的多样性，那temperature可以搞得大一点，生成的概率更加平均。
