### ISSUE TITLE
可以利用transformers库微调生成任务吗？

### ISSUE THREAD

**Issue by drxmy** [TsinghuaAI/CPM-1-Generate#51]
您好，我看到CPM-Generate已经可以用hugging face的库来加载了。那我能用transformers里面的函数来做微调吗？比如AutoModelForCausalLM。

**Comment by zzy14** [comment]
是可以的。

**Comment by ShaneTian** [comment]
HF 的 `CpmTokenizer` 和本库的 Tokenizer 不同，是什么原因呢？
