### ISSUE TITLE
generate 不使用fp16时报错

### ISSUE THREAD

**Issue by xiaofei05** [TsinghuaAI/CPM-1-Generate#53]
模型finetune时没有使用fp16, 对finetune后的模型使用 ./scripts/generate_text.sh  交互生成正常，但是去掉./scripts/generate_text.sh中的--fp16时报错：
![image](https://user-images.githubusercontent.com/26503378/122729012-498ab600-d2ab-11eb-8a5f-d894e0fb9cc5.png)

修改generate_examples.py 233行
past_key_values = [x.half() for x in past_key_values]
为
past_key_values = [x for x in past_key_values]

仍然报相同错误。

**Comment by zzy14** [comment]
您可以尝试把 generate_examples.py中`past_key_values = [x.half() for x in past_key_values]` 的half()删除。

**Comment by xiaofei05** [comment]
> 您可以尝试把 generate_examples.py中`past_key_values = [x.half() for x in past_key_values]` 的half()删除。

如题所说，仍然是相同错误

**Comment by zzy14** [comment]
您好，我们更新了一下对应的代码，测试现在是可以跑fp32的，您可以试试看

**Comment by xiaofei05** [comment]
好的，现在没有问题了，感谢！
