### ISSUE TITLE
文本分类任务的结果跟论文中相差很大。

### ISSUE THREAD

**Issue by Chunhui-Zou** [TsinghuaAI/CPM-1-Generate#67]
文本分类中，处理OCNLI的结果和论文中近似，其他两个数据集的结果相差很远。有人知道是什么原因吗
# 数据集OCNLI
EVAL 1309/2948=0.444(论文中0.442)
# 数据集TNEWS
EVAL 3280/10000=0.328(论文中0.703)
# IFLYTEK
EVAL 563 2598=0.2167

**Comment by zzy14** [comment]
可能是模型没有正确加载？您可以提供一下运行的命令。

**Comment by jerryli1981** [comment]
> > 
> 
> 在OCNLI数据集的结果是和论文中接近，其他两个数据集的结果相差很大

您好，我也发现在TNEW上的指标和论文差别比较大，请问您后来解决了吗？

**Comment by zzy14** [comment]
参考 #46 ，原始默认测试完整标签集合结果，现已改为默认测试采样标签集合结果。
