### ISSUE TITLE
请问CPM是否有相配的单个字的tokenizer

### ISSUE THREAD

**Issue by Yixiao-Song** [TsinghuaAI/CPM-1-Generate#69]
现在的tokenizer，结巴，会把句子切分为（两字、三字）词组。请问是否有tokenizer可以把句子按照单个字切开且和CPM相配的？谢谢！

**Comment by zzy14** [comment]
目前没有，tokenizer和模型是强耦合的，如果要做单字的tokenizer，就需要训一个基于该tokenizer的模型。
