### ISSUE TITLE
CPM对话模型与宣传差距很大

### ISSUE THREAD

**Issue by jinfagang** [TsinghuaAI/CPM-1-Generate#71]
![image](https://user-images.githubusercontent.com/21303438/157814063-6aaeafec-1ec1-4589-8501-d98af11c1dae.png)

无法推理一些常见的逻辑，与简单的对话模型相比没有任何特色之处

**Comment by zzy14** [comment]
您使用的应该是黄民烈老师组开源的对话模型EVA，不是CPM。EVA据了解最近有很大的更新，您可以看看他们的repo https://github.com/thu-coai/EVA。

**Comment by jinfagang** [comment]
@zzy14 某悟道的CPM2.1 EVA模型。。。。。
